version: '3'
services:
  selenoid:
    image: aerokube/selenoid:1.10.8
    container_name: selenoid
    network_mode: bridge
    shm_size: 2gb
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${PWD}/selenoid/config/:/etc/selenoid/:ro"
      - "${PWD}/selenoid/config/video/:/opt/selenoid/video/"
      - "${PWD}/selenoid/config/logs/:/opt/selenoid/logs/"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=${PWD}/selenoid/config/video/
      - TZ=Europe/Minsk
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-video-recorder-image", "selenoid/video-recorder:7.1", "-capture-driver-logs"]
    ports:
      - "4444:4444"